### ISSUE TITLE
app crashes after leaving screen

### ISSUE THREAD

**Issue by Miladt** [cafebazaar/flutter_poolakey#12]
kotlin.UninitializedPropertyAccessException: lateinit property paymentConnection has not been initialized
E/AndroidRuntime(12583): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4605)
E/AndroidRuntime(12583): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4623)
E/AndroidRuntime(12583): 	at android.app.ActivityThread.-wrap5(Unknown Source:0)
E/AndroidRuntime(12583): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
E/AndroidRuntime(12583): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(12583): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(12583): 	at android.app.ActivityThread.main(ActivityThread.java:6944)
E/AndroidRuntime(12583): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12583): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/AndroidRuntime(12583): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
E/AndroidRuntime(12583): Caused by: kotlin.UninitializedPropertyAccessException: lateinit property paymentConnection has not been initialized

**Comment by sahmadreza** [comment]
same issue

**Comment by Miladt** [comment]
Fixed by connect FlutterPoolakey in didChangeDependencies

**Comment by navidprox** [comment]
Same problem. I don't want to call `FlutterPoolakey.connect` before it's needed. If the user exits the app without `FlutterPoolakey.connect` being called, the crash happens. A fix is proposed for this: https://github.com/cafebazaar/flutter_poolakey/pull/9

**Comment by nasrabadiAM** [comment]
This problem Fixed in #9 and release in [2.1.0](https://github.com/cafebazaar/flutter_poolakey/releases/tag/2.1.0)
