### ISSUE TITLE
app crashes - possibly when there is an internet connection problem

### ISSUE THREAD

**Issue by hrmoh** [cafebazaar/flutter_poolakey#14]
It happens sometimes and I guess it might be related to the device having internet connection problems. This is what I found on debug console:

E/JavaBinder( 5318): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 180)
D/AndroidRuntime( 5318): Shutting down VM
E/AndroidRuntime( 5318): FATAL EXCEPTION: main
E/AndroidRuntime( 5318): Process: com.sppcco.tperacc, PID: 5318
E/AndroidRuntime( 5318): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 5318): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
E/AndroidRuntime( 5318): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime( 5318): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 5318): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5318): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 5318): 	... 1 more
E/AndroidRuntime( 5318): Caused by: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died, but this could also be caused by running out of binder buffe
E/AndroidRuntime( 5318): 	at android.os.BinderProxy.transactNative(Native Method)
E/AndroidRuntime( 5318): 	at android.os.BinderProxy.transact(BinderProxy.java:584)
E/AndroidRuntime( 5318): 	at com.android.vending.billing.IInAppBillingService$Stub$Proxy.isBillingSupported(IInAppBillingService.java:324)
E/AndroidRuntime( 5318): 	at ir.cafebazaar.poolakey.billing.connection.ServiceBillingConnection.isPurchaseTypeSupported(ServiceBillingConnection.kt:121)
E/AndroidRuntime( 5318): 	at ir.cafebazaar.poolakey.billing.connection.ServiceBillingConnection.onServiceConnected(ServiceBillingConnection.kt:98)
E/AndroidRuntime( 5318): 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2188)
E/AndroidRuntime( 5318): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2221)
E/AndroidRuntime( 5318): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime( 5318): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 5318): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 5318): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 5318): 	at android.app.ActivityThread.main(ActivityThread.java:7898)

**Comment by nasrabadiAM** [comment]
Which version of flutter_poolakey do you use?

**Comment by nasrabadiAM** [comment]
This issue has been fixed since version: [2.1.0](https://github.com/cafebazaar/flutter_poolakey/releases/tag/2.1.0)
