### ISSUE TITLE
Raise this error when i want to profiling

### ISSUE THREAD

**Issue by alaalfam** [cafebazaar/flutter_poolakey#17]
روی دیباگ مود و ریلیز مود همه چیز درست است و کار می کند اما زمانی که میخواهم روی پروفایل مود برنامه رو اجرا کنم با خطای زیر رو به رو میشم

e: file:///Users/developer/.pub-cache/hosted/pub.dev/flutter_poolakey-2.1.0/android/src/main/kotlin/ir/cafebazaar/flutter_poolakey/FlutterPoolakeyPlugin.kt:102:36 Unresolved reference: POOLAKEY_VERSION

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_poolakey:compileProfileKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction

**Comment by nasrabadiAM** [comment]
It seems like you're encountering an issue related to the POOLAKEY_VERSION reference. You can resolve this by adding the following code to your build.gradle file:

```groovy

benchmark {
    initWith buildTypes.release
    matchingFallbacks.add("release")
}
```
This should fix the problem. Let me know if you need any further assistance!
