### ISSUE TITLE
مشکل در اجرای فلاتیر

### ISSUE THREAD

**Issue by fazelit** [cafebazaar/flutter_poolakey#18]
سلام من وقتی این پکیج رو در فایل pubscpec.yaml قرار می دم و دستور flutter pub get میزنم دریافت میکنه اما بعدش که اجرا می کنم خطای زیر میده:

`
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.cafebazaar.Poolakey:poolakey:2.2.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/cafebazaar/Poolakey/poolakey/2.2.0/poolakey-2.2.0.pom
       - https://repo.maven.apache.org/maven2/com/github/cafebazaar/Poolakey/poolakey/2.2.0/poolakey-2.2.0.pom
       - https://storage.googleapis.com/download.flutter.io/com/github/cafebazaar/Poolakey/poolakey/2.2.0/poolakey-2.2.0.pom
       - https://jcenter.bintray.com/com/github/cafebazaar/Poolakey/poolakey/2.2.0/poolakey-2.2.0.pom
     Required by:
         project :app > project :flutter_poolakey

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 59s
Exception: Gradle task assembleDebug failed with exit code 1

`

**Comment by iranandroid** [comment]
@DHosseiny

**Comment by iranandroid** [comment]
@fazelit 
Hi, for me fix with add below line to build.gradle(Project) and sync project
`jcenter()
maven { url 'https://jitpack.io' }`

**Comment by m8811163008** [comment]
How to add this line in build.gradle?

**Comment by fazelit** [comment]
yes thank you

**Comment by nasrabadiAM** [comment]
Duplicate #24 and fixed in  [afc744a](https://github.com/cafebazaar/flutter_poolakey/commit/b76d6c95bd8a056ed9e2b632537a8528cafc744a)
