### ISSUE TITLE
Kotlin null pointer exception when Closing the app

### ISSUE THREAD

**Issue by aminnzo** [cafebazaar/flutter_poolakey#2]
Unable to destroy activity {ir.cafebazaar.flutter_poolakey_example/ir.cafebazaar.flutter_poolakey_example.MainActivity}: kotlin.KotlinNullPointerException

I've got this exception in my app and also in example app created by your team.

**Comment by manjav** [comment]
Has fixed on v1.30 and above

**Comment by ssbateni** [comment]
> Has fixed on v1.30 and above

but I get this exception on v2.0.0 too
