### ISSUE TITLE
flutter poolaky 

### ISSUE THREAD

**Issue by Elenaliiii** [cafebazaar/flutter_poolakey#24]
What should I do to fix this error?

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.cafebazaar.Poolakey:poolakey:2.2.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/cafebazaar/Poolakey/poolakey/2.2.0/poolakey-2.2.0.pom
       - https://repo.maven.apache.org/maven2/com/github/cafebazaar/Poolakey/poolakey/2.2.0/poolakey-2.2.0.pom
       - https://storage.googleapis.com/download.flutter.io/com/github/cafebazaar/Poolakey/poolakey/2.2.0/poolakey-2.2.0.pom
     Required by:
         project :app > project :flutter_poolakey

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by hadisadegh** [comment]
Adding the JitPack Repository
Open your project's build.gradle file (the top-level file in the project root).

Go to the allprojects section and add the JitPack repository to the repositories block:
`allprojects {
    repositories {
        google()
        mavenCentral()
        // add JitPack
        maven { url 'https://jitpack.io' }
    }
}
`

**Comment by nasrabadiAM** [comment]
This issue has been addressed by updating the README in commit  [afc744a](https://github.com/cafebazaar/flutter_poolakey/commit/b76d6c95bd8a056ed9e2b632537a8528cafc744a). The README now includes the necessary instructions to fix the error. Please follow the updated guidelines, and let us know if you encounter any more issues.

Thank you for your understanding!
