### ISSUE TITLE
Poolakey for iOS and Web

### ISSUE THREAD

**Issue by mehrdadmmb2** [cafebazaar/flutter_poolakey#25]
ای کاش پولکی فلاتر برای ios و وب هم منتشر توسعه داده بشه
درسته که کافه بازار فقط روی اندرویده اما برای پلتفرم های دیگه بشه از کیف پول کاربر برداشت کرد

**Comment by nasrabadiAM** [comment]
سلام مهرداد جان، ممنون بابت پیشنهادت، 
من این رو با تیم مربوطه مطرح میکنم و جوابش رو بهت میدم.

**Comment by nasrabadiAM** [comment]
به زودی تیم فروش باهاتون ارتباط میگیرن که مساله رو دقیقتر کنند و این موضوع رو جلو ببریم، 
من فعلا این ایشو رو میبندم اما اگر موردی بود، خوشحال میشم درباره‌اش صحبت کنیم.
