### ISSUE TITLE
A problem occurred configuring project ':flutter_poolakey'.

### ISSUE THREAD

**Issue by hosseinipour** [cafebazaar/flutter_poolakey#27]
سلام
بعد از اضافه کردم پکیج `flutter_poolakey` پروژه به طور کلی ران نمیشه، و خطای زیر رو میده:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':flutter_poolakey'.
> com.android.builder.errors.EvalIssueException: Build Type 'debug' contains custom BuildConfig fields, but the feature is disabled.
  To enable the feature, add the following to your module-level build.gradle:
  `android.buildFeatures.buildConfig true`

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 7s
Error: Gradle task assembleDebug failed with exit code 1
```

از پکیج `flutter_poolakey` ورژن `2.2.0` استفاده کردم و ورژن فلاتر `3.24.3` هست.
روی پروژه کاملا خالی هم تست کردم، به محظ اضافه کردن پکیج به `pubspec.yaml` این مشکل پیش میاد و نیاز به فراخوانی کلاس هم نیست.

در ضمن کاری که در این خطا گفته یعنی اضافه کردن `buildConfig true` رو هم انجام دادم و نتیجه تغییری نکرد.

**Comment by nasrabadiAM** [comment]
لطفا پروژه‌ای که ساختید رو باهامون به اشتراک میزارید؟

**Comment by AfshinNajafi74** [comment]
سلام
من هم با این مشکل مواجه هستم

**Comment by EmperorofWeb** [comment]
> سلام من هم با این مشکل مواجه هستم

من ورژن gradle رو 7 (7.6.4) گذاشتم مشکل حل شد.

**Comment by hosseinipour** [comment]
> سلام من هم با این مشکل مواجه هستم

من ورژن gradle رو 7 (7.6.4) گذاشتم مشکل حل شد.

**Comment by Saeed-7** [comment]
سلام

در پوشه اندروید و فایل app.build.gradle پروژه تون مقدار buildConfig را مشابه زیر رو اضافی کنید:
```
android {
     ....
     
     buildFeatures {
             buildConfig = true
     }
}
```
اگر از gradle های ورژن 8 به بعد استفاده میکنید احتمالا با خطای namespace مواجه میشید که در این صورت باید در پکیج poolakey تغییرات ایجاد کنید و از حالت استاندارد خارجش کنید!
در فایل app.build.gradle از پوشه android در flutter_poolakey-2.2.0 در خط اول بلاک android مقدار namespace را وارد کنید:
```
android {
    namespace = "ir.cafebazaar.flutter_poolakey"
    ...
}
```
امیدوارم جواب بده. موفق باشید :)
