### ISSUE TITLE
Fix The Package for android 12 compatibility 

### ISSUE THREAD

**Issue by Abraham-EH** [cafebazaar/flutter_poolakey#3]
this two weeks i was drowned and frustrated because i thought i missed up ☹️ now i just simply removed the poolakey Package and everything works as usual , fix the demn thing for supporting android 12

**Comment by alikhajavi74** [comment]
change your target api from 31 to 30  your problem will solve.
but yeah you right they should solve this issue.

**Comment by manjav** [comment]
It has fixed on v2.0.0
