### ISSUE TITLE
Conflict with Myket_iap package

### ISSUE THREAD

**Issue by javaherisaber** [cafebazaar/flutter_poolakey#4]
I want to use both Myket and Cafebazaar plugins for my in-app purchases.
Because both packages contain `IInAppBillingService.aidl` flutter build has an error.
`Duplicate source file detected`

Please fix this issue or give me a clue what to do

**Comment by hsiami** [comment]
> I want to use both Myket and Cafebazaar plugins for my in-app purchases. Because both packages contain `IInAppBillingService.aidl` flutter build has an error. `Duplicate source file detected`
> 
> Please fix this issue or give me a clue what to do

سلام راه حلی برای این مشکلتون پیدا کردید؟

**Comment by javaherisaber** [comment]
@hsiami 
مجبور شدم یه متد چنل بسازم و کدهای جفت کتابخونه ها رو بیارم داخل پروژه!

**Comment by AliZahmatkesh** [comment]
سلام من وقتی میخام از پکیج استفاده کنم رو هر ایتم که کلیک میشه 
از سمت بازار مینویسه این ایتم وجود ندارد
موارد و درست انجام میدم اما همچنان همین اروره 
ممنون میشم راهنمایی کنید

![photo_2022-04-05_23-23-34](https://user-images.githubusercontent.com/87716028/163006156-64944ed4-e706-49f2-ac06-ff98701ef053.jpg)
![image_2022-04-05_23-24-55](https://user-images.githubusercontent.com/87716028/163006168-e2a4b856-aa73-4ac1-8bc4-7f83560590be.png)

**Comment by manjav** [comment]
> م از پکیج استفاده کنم رو هر ایتم که کلیک میشه
> از سمت بازار مینویسه این ایتم وجود ندارد
> موارد و درست انجام میدم اما همچنان همین اروره
> ممنون میشم راهنمایی کنید

این مشکل فنی نیست به سیاست های استورها مربوط میشه ازتون خواهش می کنم از طریق پنل توسعه‌دهندگان مشکلتون رو  مطرح بفرمایید.

**Comment by manjav** [comment]
> سلام من وقتی میخام از پکیج استفاده کنم رو هر ایتم که کلیک میشه از سمت بازار مینویسه این ایتم وجود ندارد موارد و درست انجام میدم اما همچنان همین اروره ممنون میشم راهنمایی کنید
> 
> ![photo_2022-04-05_23-23-34](https://user-images.githubusercontent.com/87716028/163006156-64944ed4-e706-49f2-ac06-ff98701ef053.jpg) ![image_2022-04-05_23-24-55](https://user-images.githubusercontent.com/87716028/163006168-e2a4b856-aa73-4ac1-8bc4-7f83560590be.png)

از نمونه اپ داخل منبع استفاده کنید در صورتی که بدون مشکل خرید انجام می‌شود یا در پیشخان محصول خود را معرفی نکرده‌اید یا packagename اپ اشتباه است.
