### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by AliZahmatkesh** [cafebazaar/flutter_poolakey#6]
سلام 
وقتی روی هر ایتم کلیک میکنم
از سمت بازار پیغام این ایتم وجود ندارد میده
ممنون میشم راهنمایی کنید
![photo_2022-04-05_23-23-34](https://user-images.githubusercontent.com/87716028/163007175-256a6e04-0425-4dee-8d3b-28be4417afa8.jpg)
![image_2022-04-05_23-24-55](https://user-images.githubusercontent.com/87716028/163007184-9e2a1d0b-8aba-432f-8b3b-e0dcf0a30c97.png)

**Comment by msmoradi** [comment]
سلام
لطفا چک کنید شناسه ای که وارد کردید تو پنل توسعه دهندگان بازار وجود داشته باشه و مطمئن بشیم که مقداری که تو ستون "شناسه‌ی کالا" هست رو تو فانکشن purchase وارد کرده باشیم .

**Comment by manjav** [comment]
از نمونه اپ داخل منبع استفاده کنید در صورتی که بدون مشکل خرید انجام می‌شود یا در پیشخان محصول خود را معرفی نکرده‌اید یا packagename اپ اشتباه است.

**Comment by AliZahmatkesh** [comment]
از نمونه منبع داخل هم استفاده میکنم و شناسه کالا رو تغیر میدم و باز هم همین ارور میده

**Comment by manjav** [comment]
آیا بدون هیچ تغییر پروژه نمونه کار می کند؟

**Comment by AliZahmatkesh** [comment]
packagename  اپ کجا باید تعریف کرد؟

**Comment by AliZahmatkesh** [comment]
من طبق مستندات خود سایت پولکی پیش رفتم اما به خطا خورده

**Comment by manjav** [comment]
> آیا بدون هیچ تغییر پروژه نمونه کار می کند؟

یاسخ این سوال رو هنوز دریافت نکردم

**Comment by AliZahmatkesh** [comment]
![image_2022-04-26_21-45-09](https://user-images.githubusercontent.com/87716028/165356283-3f729bd0-d2ab-49cd-ba65-c616b98f828c.png)
![image_2022-04-26_21-45-20](https://user-images.githubusercontent.com/87716028/165356298-ef710127-2f4d-457e-b645-c595690b158e.png)
ببینید موارد دقیق انجام شده اما بازم وقتی رو ایتم کلیک میشه میگه محصولی وجود ندارد

**Comment by manjav** [comment]
> ![image_2022-04-26_21-45-09](https://user-images.githubusercontent.com/87716028/165356283-3f729bd0-d2ab-49cd-ba65-c616b98f828c.png) ![image_2022-04-26_21-45-20](https://user-images.githubusercontent.com/87716028/165356298-ef710127-2f4d-457e-b645-c595690b158e.png) ببینید موارد دقیق انجام شده اما بازم وقتی رو ایتم کلیک میشه میگه محصولی وجود ندارد

هنوز پاسخ سوال قبل دریافت نشده است

**Comment by manjav** [comment]
> packagename اپ کجا باید تعریف کرد؟

**Comment by manjav** [comment]
> > packagename اپ کجا باید تعریف کرد؟
این مسئله در مورد تکنولوژی فلاتر بوده و ارتباطی به این پروژه ندارد.
https://stackoverflow.com/questions/51534616/how-to-change-package-name-in-flutter

**Comment by AliZahmatkesh** [comment]
> 

الان این ارور بخاطر همین پکیج نیم هست؟

**Comment by AliZahmatkesh** [comment]
> Reference in ne

بله کار میکنه

**Comment by AliZahmatkesh** [comment]
منتهی من سعی کردم از کد همون سورس منبع استفاده کنم اما اوکی نمیشد و محصول رو شناسایی نمیکرد

**Comment by AliZahmatkesh** [comment]
![image_2022-04-26_22-09-31](https://user-images.githubusercontent.com/87716028/165359984-27558dc7-15cf-4833-910c-b078aa740152.png)
پکیج نیم این اپ درحال حاضر اینه
صرفا یک اپ تست برای اتصال به بازاره که همچنان تو خطاست

**Comment by manjav** [comment]
> 
این به این معنی هست که پلاگین مشکلی نداره و شما در تغییراتی که در پروژه ایجاد می‌کنید احتمالا اشتباهی رخ داده. سه نوع تغییرات بایست داشته باشید در انجام مراحل دقت فرمایید.

packagename 
base64RSAkey
productIds

**Comment by manjav** [comment]
> بازاره که همچنان تو خطاس

متأسفانه ما نمی‌توانیم در تغییراتی که در پروژه خود انجام می دهید شما را همراهی کنیم. لطفا در معرفی اپ در پیشخان یا تغییرات در پروژه نمونه دقت بیشتری مبذول فرمایید

**Comment by AliZahmatkesh** [comment]
ببینید من متوجه نشدم تغیرات
packagename
base64RSAkey
کجا هستند اخه تو مستندات ذکر نشده 
میشه یک توضیح بدید؟

**Comment by manjav** [comment]
این پیام رو من ندیدم و پوزش می خوام

تغییر packagename برای فلاتر رو در اینترنت جستجو کنید و base64RSAkey در پروژه rsaKey رو جستجو کنید.
