### ISSUE TITLE
Type mismatch: inferred type is BinaryMessenger? but BinaryMessenger was expected

### ISSUE THREAD

**Issue by kondori-reza1990** [cafebazaar/flutter_poolakey#7]
سلام و خداقوت
طبق فایل راهنما کدها توی برنامه قرار گرفته ولی موقع اجرا خطای زیر رو میده:

> `flutter\.pub-cache\hosted\pub.dartlang.org\flutter_poolakey-2.0.0\android\src\main\kotlin\ir\cafebazaar\flutter_poolakey\FlutterPoolakeyPlugin.kt: (41, 33): Type mismatch: inferred type is BinaryMessenger? but BinaryMessenger was expected`

لطفا راهنمایی بفرمایید.

**Comment by Saeeed-B** [comment]
سلام باید پیکج طبق لینک زیر اصلاح بشه :

[https://github.com/flutter/flutter/issues/45231#issuecomment-604331301](https://github.com/flutter/flutter/issues/45231#issuecomment-604331301)

نمیدونم واقعا چرا پکیجتون رو پشتیبانی نمیکنید ، !! 

@manjav
