### ISSUE TITLE
ناسازگاری با ورژن 3 فلاتر

### ISSUE THREAD

**Issue by AhmadFalahian** [cafebazaar/flutter_poolakey#8]
این پکیج با ورژن 3 فلاتر ناسازگار است 
لطفا پیگیری های لازم را انجام دهید

**Comment by manjav** [comment]
با تشکر از موردی که فرمودید بزودی نسخه جدید ارائه خواهد شد.

**Comment by AhmadFalahian** [comment]
با تشکر از شما

**Comment by manjav** [comment]
لطفا خطایی که مشاهده می کنید رو هم اینجا بفرستید

**Comment by manjav** [comment]
مشکل در نسخه 2.0.1 رفع گردید
